# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    # driver: "imagick"
    driver: "gd"

    filter_sets:
        biensml:
            quality: 75
            filters:
                thumbnail:
                    size: [300, 300]
                    mode: outbond
                    allow_upscale: true
                
        biensxs:
            quality: 75
            filters:
                thumbnail:
                    size: [50, 50]
                    mode: outbond
                    allow_upscale: true