vich_uploader:
    db_driver: orm

    mappings:
        equipments_images:
            uri_prefix: /images/equipments
            upload_destination: '%kernel.project_dir%/public/images/equipments'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
